name: module3_task0
on:
  push:
    branches: 
      - main

  schedule:
    - cron: '10 10 * * *'

jobs:
  building:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: cd module3_task0 && make help
